[features]
seeds = false
skip-lint = false
[programs.localnet]
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[programs.devnet]
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[programs.mainnet]
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/rubenschaller/kulture/keys/BLDRZQiqt4ESPz12L9mt4XTBjeEfjoBopGPDMA36KtuZ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
