[features]
seeds = false
skip-lint = false
[programs.localnet]
royalty_redemptions = "4pV5PQe2AH3r8M9sZ1seMHwhwCyLBdWbaiuWMphXSfaL"
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[programs.devnet]
royalty_redemptions = "4pV5PQe2AH3r8M9sZ1seMHwhwCyLBdWbaiuWMphXSfaL"
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[programs.mainnet]
royalty_redemptions = "4pV5PQe2AH3r8M9sZ1seMHwhwCyLBdWbaiuWMphXSfaL"
repay_royalties_contract = "9ZskGH9wtdwM9UXjBq1KDwuaLfrZyPChz41Hx7NWhTFf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rubenschaller/kulture/keys/BLDRZQiqt4ESPz12L9mt4XTBjeEfjoBopGPDMA36KtuZ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
